### ISSUE TITLE
Ensure StringIO seek positions are modified before uploading analysis results

### ISSUE THREAD

**Issue by leeren** [Yelp/amira#14]
https://github.com/Yelp/amira/blob/2d44ee2e0004cd4b069d87f7655465f7e3bd2d75/amira/amira.py#L166

Currently, this is only done once after finishing the OSXCollector results analysis. Before calling `upload_results` from each individual `results_uploader`, the underlying StringIO objects of `results` should all call `seek(0)` again in case any of their associated stream positions have been modified by any other `results_uploader`.

**Comment by piax93** [comment]
Addressed by chance in 3dbb942ad64a58643346c03cb023b391d61c602c
